name: 🌐 IP INFO CHECK

on:
  push:
    branches: [ "main" ]

jobs:
  ip-check:
    runs-on: ubuntu-latest

    steps:
      - name: 🔎 Get Public IP Info
        run: |
          echo "🌍 Fetching runner IP info..."
          curl ipinfo.io