name: 🚀 Deploy via SSH

on:
  push:
    branches:
      - lec

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v4

      - name: 🔐 Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: 🚀 Run Deploy Script on Server
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} \
          "bash /var/www/test-devOps-git/deploy.sh"